###  ---------------- SUCURSALES -----------------------
GET http://localhost:8080/Branches HTTP/1.1

###
GET http://localhost:3000/allBranches/1 HTTP/1.1

###
POST http://localhost:8080/Branches HTTP/1.1
Content-Type: application/json

{
    "phone": 3415555555,
    "address": "San Martin 6001"
}

###
PATCH  http://localhost:8080/allBranches/1 HTTP/1.1
Content-Type: application/json

{
    "phone": 3412222333,
}

###
DELETE http://localhost:8080/allBranches/4 HTTP/1.1



###  ---------------- PRODUCTOS -----------------------
GET http://localhost:3000/allProducto HTTP/1.1

###
GET http://localhost:3000/allProducto/2 HTTP/1.1

###
POST http://localhost:3000/allProducto HTTP/1.1
Content-Type: application/json

{
    "descripcion": "Esmalte Distincion",
    "precio": 15000,
    "stock": 18
}

###
PUT http://localhost:3000/allProducto/3 HTTP/1.1
Content-Type: application/json

{
    "descripcion": "Esmalte Casablanca",
    "precio": 15000,
    "stock": 18
}

###
DELETE http://localhost:3000/allProducto/3 HTTP/1.1



###  ---------------- USUARIOS -----------------------
GET http://localhost:8080/Users HTTP/1.1

###
GET http://localhost:8080/allUsers/name/Alex123 HTTP/1.1

###
GET http://localhost:8080/allUsers/level/2 HTTP/1.1
###
POST http://localhost:8080/Users HTTP/1.1
Content-Type: application/json

{
    "userName": "admin",
    "pswHash": "admin",
    "level": 1,
    "email": "admin@gmail.com"
}
###
POST http://localhost:8080/Users/login HTTP/1.1
Content-Type: application/json

{
    "userName": "vendedor",
    "pswHash": "vendedor"
}
###
PUT http://localhost:3000/allUsuario/3 HTTP/1.1
Content-Type: application/json

{
    "username": "Luka123456",
    "email": "luka@gmail.com",
    "psw": "123"
}
###
DELETE http://localhost:8080/allUsers/1 HTTP/1.1


###  ---------------- Clientes -----------------------
GET http://localhost:8080/Clients HTTP/1.1

###
GET http://localhost:8080/allClients/2 HTTP/1.1

###
POST http://localhost:8080/Clients HTTP/1.1
Content-Type: application/json

{
    "dni": 94984636,
    "name": "Alex Birchmeyer"
}

###
PATCH  http://localhost:8080/allClients/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Alex"

}

###
DELETE http://localhost:3000/allUsuario/3 HTTP/1.1

###  ---------------- Clientes -----------------------
GET http://localhost:8080/allLevels HTTP/1.1

###
GET http://localhost:8080/allClients/2 HTTP/1.1

###
POST http://localhost:8080/allLevels HTTP/1.1
Content-Type: application/json

{
    "description": "Cliente"
}

###
PATCH  http://localhost:8080/allClients/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Alex"

}

###
DELETE http://localhost:3000/allUsuario/3 HTTP/1.1


###  ---------------- Productos -----------------------
GET http://localhost:8080/allSuppliers HTTP/1.1

###
GET http://localhost:8080/allProducts/2 HTTP/1.1

###
POST http://localhost:8080/allSuppliers HTTP/1.1
Content-Type: application/json

{
    "cuit": 23949846369,
    "name": "Alex Birchmeyer"
}

###
PATCH  http://localhost:8080/allProducts/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Alex"

}

###
DELETE http://localhost:3000/allProducts/3 HTTP/1.1

###  ---------------- proveedores -----------------------
GET http://localhost:8080/allSuppliers HTTP/1.1

###
POST http://localhost:8080/allSuppliers HTTP/1.1
Content-Type: application/json

{
    "cuit": 23949846369,
    "name": "Alex Birchmeyer",
    "address": "San Martin 6001",
    "phone": 3412742584
}
###
DELETE http://localhost:8080/allSuppliers/2 HTTP/1.1

###
PATCH  http://localhost:8080/allSuppliers/4 HTTP/1.1
Content-Type: application/json

{
    "cuit": 123456789
}
###  ---------------- Productos -----------------------
GET http://localhost:8080/allProducts HTTP/1.1

###
POST http://localhost:8080/allSuppliers HTTP/1.1
Content-Type: application/json

{
    "cuit": 23949846369,
    "name": "Alex Birchmeyer",
    "address": "San Martin 6001",
    "phone": 3412742584
}
###
DELETE http://localhost:8080/allSuppliers/2 HTTP/1.1

###
PATCH  http://localhost:8080/allProducts/2 HTTP/1.1
Content-Type: application/json

{
    "description": "Latex Acrilico 1lt"
}

###  ---------------- Empleado -----------------------
GET http://localhost:8080/allEmployees HTTP/1.1

###
POST http://localhost:8080/allEmployees HTTP/1.1
Content-Type: application/json

{
    "name": "Alex Birchmeyer",
    "salary": 500000,
    "phone": 3412742584,
    "dni": 94984636
}

###  ---------------- Ventas -----------------------
GET http://localhost:8080/allSales HTTP/1.1

###
POST http://localhost:8080/allSales HTTP/1.1
Content-Type: application/json

{
    "idClient": 2,
    "idEmp": 3,
    "idBranch": 1,
    "total": 100000
}

###  ---------------- renglon -----------------------
GET http://localhost:8080/Users HTTP/1.1

###
POST http://localhost:8080/allRows HTTP/1.1
Content-Type: application/json

{
    "amount": 1,
    "idSale": 6,
    "idProduct": 2,
    "description": "Latex Acriico 4 lt",
    "price": 120000,
    "total": 120000
}